---
- name: Setup NSQ server with required packages
  hosts: dockube-all
  #remote_user: '{{ remote_user }}'
  sudo: yes

  vars:
    app_name: dockube-nsq
    nsq_network_interface: dockube-net
    nsq_network_ip_protocol: ipv4
    nsq_network_address: 172.212.0.6

  roles:
    - nsq
