---
- import_playbook: ansible-pretasks.yaml  playbook_host=dockube-nfs

- name: Setup nsqlookupd service
  hosts: dockube-nfs
  remote_user: '{{ remote_user }}'
  become: yes

  vars:
    app_name: nsqlookupd
    nsq_network_address: 172.212.0.11  #'{{ ansible_default_ipv4.address }}'

  roles:
    #- consul
    - nsq
