---
- import_playbook: ansible-pretasks.yaml  playbook_host=dockube-node

- name: Setup nsqd service
  hosts: dockube-node
  remote_user: '{{ remote_user }}'
  become: yes
  become_user: root

  vars:
    app_name: nsqd
    nsqd_role: true
    nsqlookupd_role: true
    nsq_network_address: 172.212.0.8   #'{{ ansible_default_ipv4.address }}'

  roles:
    #- consul
    - nsq
