---
- import_playbook: ansible-pretasks.yaml  playbook_host=dockube-all

- name: Setup Golang
  hosts: dockube-all
  remote_user: '{{ remote_user }}'
  become: yes

  vars:
    app_name: golang
    golang_version: 1.11.1

  roles:
    - golang
