---
- import_playbook: ansible-pretasks.yaml  playbook_host=tag_nsq-nsqd

- name: Setup nsqd service
  hosts: tag_nsq-nsqd
  remote_user: '{{ remote_user }}'
  become: yes

  vars:
    app_name: nsqd
    nsq_network_address: '{{ ansible_default_ipv4.address }}'

  roles:
    - consul
    - nsq
