---
- import_playbook: ansible-pretasks.yaml  playbook_host=tag_docker

- name: Setup Docker & Docker Compose
  hosts: tag_docker
  remote_user: '{{ remote_user }}'
  become: yes
  become_user: root

  vars:
    app_name: docker
    docker_edition: ce
    docker_channel: ["stable"]
    docker_version: "18.06.1"
    docker_compose_version: "1.23.2"

  roles:
    - docker
