---
- import_playbook: ansible-pretasks.yaml  playbook_host=tag_nsq-nsqlookupd

- name: Setup nsqlookupd service
  hosts: tag_nsq-nsqlookupd
  remote_user: '{{ remote_user }}'
  become: yes

  vars:
    app_name: nsqlookupd
    nsq_network_address: '{{ ansible_default_ipv4.address }}'

  roles:
    - consul
    - nsq
