---
# vars file for ansible-golang

golang_release: "go{{ golang_version }}.{{ golang_os }}-{{ golang_arch }}"
golang_release_archive: "{{ golang_release }}.tar.gz"
golang_download_url: "https://storage.googleapis.com/golang/{{ golang_release_archive }}"
