ARG PORTAINER_VERSION=1.16.5
FROM portainer/portainer:${PORTAINER_VERSION}

# ================================================================================================
#  Inspiration: Docker Framework (https://github.com/dockube/dockube)
#               Dwi Fahni Denni <zeroc0d3.team@gmail.com>
# ================================================================================================

MAINTAINER "ZeroC0D3 Team <zeroc0d3.team@gmail.com>"

VOLUME /data

EXPOSE 9000
CMD []
