---
# handlers file for ansible-nsq

- name: reload daemon
  command: systemctl daemon-reload

- name: reload nsqd
  service: name=nsqd state=reloaded enabled=yes

- name: reload nsqadmin
  service: name=nsqadmin state=reloaded enabled=yes

- name: restart nsqd
  service: name=nsqd state=restarted enabled=yes

- name: restart nsqadmin
  service: name=nsqadmin state=restarted enabled=yes

- name: restart nsqlookupd
  service: name=nsqlookupd state=restarted enabled=yes
